# Generated by Django 5.1.2 on 2025-10-23 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0005_remove_emaillog_template_emailcampaign_user_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcampaign",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="email_campaigns", to="campaign.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="email_logs", to="campaign.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="emailsendcandidate",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="email_send_candidates", to="campaign.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="email_templates", to="campaign.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="recipients", to="campaign.userprofile"
            ),
        ),
    ]
