# Generated by Django 5.1.2 on 2025-10-23 14:30

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0006_alter_emailcampaign_user_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="smtp_password",
            field=encrypted_model_fields.fields.EncryptedCharField(max_length=255),
        ),
    ]
