# Generated by Django 5.2.7 on 2025-10-23 20:21

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0007_alter_userprofile_smtp_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="direct_send",
            field=models.BooleanField(
                default=False, help_text="Send emails directly to recipient mail servers without using SMTP relay"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="smtp_host",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="smtp_password",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="smtp_username",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
