# Generated by Django 5.1.2 on 2025-10-23 20:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0008_add_direct_send_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailsendcandidate",
            name="tracking_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.CreateModel(
            name="CampaignStatistics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_recipients", models.IntegerField(default=0)),
                ("sent_count", models.IntegerField(default=0)),
                ("delivered_count", models.IntegerField(default=0)),
                ("opened_count", models.IntegerField(default=0)),
                ("clicked_count", models.IntegerField(default=0)),
                ("bounced_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("complained_count", models.IntegerField(default=0)),
                ("unique_opens", models.IntegerField(default=0)),
                ("unique_clicks", models.IntegerField(default=0)),
                ("delivery_rate", models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ("open_rate", models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ("click_rate", models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ("bounce_rate", models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="statistics", to="campaign.emailcampaign"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("bounced", "Bounced"),
                            ("failed", "Failed"),
                            ("complained", "Spam Complaint"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "email_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="events", to="campaign.emailsendcandidate"
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["email_candidate", "event_type"], name="campaign_em_email_c_44157a_idx"),
                    models.Index(fields=["event_type", "timestamp"], name="campaign_em_event_t_61f007_idx"),
                ],
            },
        ),
    ]
